Game REST API
Oleksandr-Eleks/who-am-i pull request #49
Opened 2022-05-05 19:40 UTC by sergvasylchak

Migrate to Spring Boot
Game REST API

2022-05-05 20:42 UTC, maksym-kit requested changes

2022-05-05 20:42 UTC, maksym-kit commented on src/main/java/com/eleks/academy/whoami/configuration/ServerProperties.java
>  public class ServerProperties {
Consider using Java's `record` instead of a `class`

2022-05-05 20:42 UTC, maksym-kit commented on src/main/java/com/eleks/academy/whoami/core/impl/PersistentGame.java
> +		this.turns.add(hostPlayer);
What is the concept of a host player?

2022-05-05 20:42 UTC, maksym-kit commented on src/main/java/com/eleks/academy/whoami/core/Player.java
> +
What is the purpose of this method?

2022-05-05 20:42 UTC, maksym-kit commented on src/main/java/com/eleks/academy/whoami/core/Game.java
> +	}
Are you sure that this method should return `String`? Looks more like it should return some `Collection` or `Iterable`.

2022-05-05 20:42 UTC, maksym-kit commented on src/main/java/com/eleks/academy/whoami/controller/GameController.java
> +	public ResponseEntity<GameDetails> startGame(@PathVariable("id") String id,
Please, avoid using `PATCH` method without `application/json+patch` header. Please, use `POST` method instead. `POST`, not `PATCH` has been meant to be used in scenarios, where some long-running jobs are being started.

2022-05-05 20:42 UTC, maksym-kit commented on src/main/java/com/eleks/academy/whoami/core/impl/PersistentGame.java
> +	private Integer currentPlayerIndex;
Instances of this class are stateful and are being used by multiple threads. Please, make this class thread-safe.

Also, please, consider using Deque for managing game states. Please, consider replacing `GameSatus` with, i.e. hierarchy of sealed classes:
```mermaid
classDiagram
    GameStatus <|.. WaitingForPlayers
    GameStatus <|.. SuggestingCharacters
    GameStatus <|.. ProcessingQuestion
    class GameStatus {
    }
    class WaitingForPlayers {
    }
    class SuggestingCharacters {
    }
    class ProcessingQuestion {
        -Deque~Player~: turnOrder
    }
    ProcessingQuestion o-- Player
```
And keep the next status transition:
```mermaid
stateDiagram
    [*] --> WaitingForPlayers
    WaitingForPlayers --> SuggestingCharacters
    SuggestingCharacters --> ProcessingQuestion
    ProcessingQuestion --> ProcessingQuestion
    ProcessingQuestion --> [*]
```
Doing something similar should greatly simplify keeping game state consistent and atomic.

2022-05-09 17:42 UTC, sergvasylchak commented on src/main/java/com/eleks/academy/whoami/core/Game.java
> +	}
This method was designed for presentational purposes only.

2022-05-10 11:24 UTC, maksym-kit approved these changes

2022-05-10 12:28 UTC, MykolaPankiv approved these changes

2022-05-10 12:28 UTC, merged